namespace: muradm
name: linode
version: 0.2.5
readme: README.md
authors:
    - muradm <mail@muradm.net> (@muradm)

description: Ansible collection with tools to manage Linode Cloud.

license:
    - Apache-2.0

tags:
    - cloud
    - linode

repository: http://github.com/muradm/ansible-linode-cloud

documentation: http://github.com/muradm/ansible-linode-cloud

homepage: http://github.com/muradm/ansible-linode-cloud

issues: http://github.com/muradm/ansible-linode-cloud/issues

build_ignore:
    - '.vscode'
    - '.venv'
