---
- name: create
  instance:
    label: "{{ linode_label | default(inventory_hostname) | mandatory }}"
    region: "{{ linode_region | mandatory }}"
    type: "{{ linode_type | mandatory }}"
    image: "{{ linode_image | mandatory }}"
    tags: "{{ linode_tags | default(group_names) }}"
    authorized_keys: "{{ linode_authorized_keys | default([]) }}"
    ipv4_public_rdns: "{{ linode_ipv4_public_rdns | default(omit) }}"
    private_ip: "{{ linode_private_ip | default(false) }}"
    state: present
  register: result

- name: record
  set_fact:
    cacheable: yes
    ansible_host: "{{ result.instance.ipv4 | ansible.netcommon.ipaddr('public') | first }}"
    ansible_user: root
    ansible_linode_instance: "{{ result.instance }}"
    ansible_private_ipv4_address: "{{ result.instance.ipv4 | ansible.netcommon.ipaddr('private') | first | default(omit) }}"
